walls:
  - name: "table"
    x_thickness: 0.913
    y_thickness: 0.913
    z_thickness: 0.04
    qx: 0
    qy: 0
    qz: 0
    qw: 1
    x: 0.92
    y: 0.014
    z: 0.755
    frame_id: world
  - name: "wall"
    x_thickness: 0.05
    y_thickness: 2
    z_thickness: 2
    qx: 0
    qy: 0
    qz: 0
    qw: 1
    x: 2.6
    y: 2.3
    z: -0.0255
    frame_id: world
