walls:
  - name: "table"
    x_thickness: 0.913
    y_thickness: 0.913
    z_thickness: 0.04
    qx: 0
    qy: 0
    qz: 0
    qw: 1
    x: 1.0
    y: 0.0
    z: 0.675
    frame_id: world
  - name: "wall"
    x_thickness: 0.05
    y_thickness: 2
    z_thickness: 2
    qx: 0
    qy: 0
    qz: 0
    qw: 1
    x: 2.6
    y: 2.3
    z: -100
    frame_id: world
