// Generated by gencpp from file world_manager_msgs/AddMeshResponse.msg
// DO NOT EDIT!


#ifndef WORLD_MANAGER_MSGS_MESSAGE_ADDMESHRESPONSE_H
#define WORLD_MANAGER_MSGS_MESSAGE_ADDMESHRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace world_manager_msgs
{
template <class ContainerAllocator>
struct AddMeshResponse_
{
  typedef AddMeshResponse_<ContainerAllocator> Type;

  AddMeshResponse_()
    {
    }
  AddMeshResponse_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::world_manager_msgs::AddMeshResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::world_manager_msgs::AddMeshResponse_<ContainerAllocator> const> ConstPtr;

}; // struct AddMeshResponse_

typedef ::world_manager_msgs::AddMeshResponse_<std::allocator<void> > AddMeshResponse;

typedef boost::shared_ptr< ::world_manager_msgs::AddMeshResponse > AddMeshResponsePtr;
typedef boost::shared_ptr< ::world_manager_msgs::AddMeshResponse const> AddMeshResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::world_manager_msgs::AddMeshResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::world_manager_msgs::AddMeshResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace world_manager_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'world_manager_msgs': ['/home/student/smoothiebot_ws/src/world_manager/world_manager_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::world_manager_msgs::AddMeshResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::world_manager_msgs::AddMeshResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::world_manager_msgs::AddMeshResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::world_manager_msgs::AddMeshResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::world_manager_msgs::AddMeshResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::world_manager_msgs::AddMeshResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::world_manager_msgs::AddMeshResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::world_manager_msgs::AddMeshResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::world_manager_msgs::AddMeshResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "world_manager_msgs/AddMeshResponse";
  }

  static const char* value(const ::world_manager_msgs::AddMeshResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::world_manager_msgs::AddMeshResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
";
  }

  static const char* value(const ::world_manager_msgs::AddMeshResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::world_manager_msgs::AddMeshResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AddMeshResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::world_manager_msgs::AddMeshResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::world_manager_msgs::AddMeshResponse_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // WORLD_MANAGER_MSGS_MESSAGE_ADDMESHRESPONSE_H
