// Generated by gencpp from file world_manager_msgs/AddMesh.msg
// DO NOT EDIT!


#ifndef WORLD_MANAGER_MSGS_MESSAGE_ADDMESH_H
#define WORLD_MANAGER_MSGS_MESSAGE_ADDMESH_H

#include <ros/service_traits.h>


#include <world_manager_msgs/AddMeshRequest.h>
#include <world_manager_msgs/AddMeshResponse.h>


namespace world_manager_msgs
{

struct AddMesh
{

typedef AddMeshRequest Request;
typedef AddMeshResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddMesh
} // namespace world_manager_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::world_manager_msgs::AddMesh > {
  static const char* value()
  {
    return "ab9fb1b3836095aff25e5ff73555f6d8";
  }

  static const char* value(const ::world_manager_msgs::AddMesh&) { return value(); }
};

template<>
struct DataType< ::world_manager_msgs::AddMesh > {
  static const char* value()
  {
    return "world_manager_msgs/AddMesh";
  }

  static const char* value(const ::world_manager_msgs::AddMesh&) { return value(); }
};


// service_traits::MD5Sum< ::world_manager_msgs::AddMeshRequest> should match 
// service_traits::MD5Sum< ::world_manager_msgs::AddMesh > 
template<>
struct MD5Sum< ::world_manager_msgs::AddMeshRequest>
{
  static const char* value()
  {
    return MD5Sum< ::world_manager_msgs::AddMesh >::value();
  }
  static const char* value(const ::world_manager_msgs::AddMeshRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::world_manager_msgs::AddMeshRequest> should match 
// service_traits::DataType< ::world_manager_msgs::AddMesh > 
template<>
struct DataType< ::world_manager_msgs::AddMeshRequest>
{
  static const char* value()
  {
    return DataType< ::world_manager_msgs::AddMesh >::value();
  }
  static const char* value(const ::world_manager_msgs::AddMeshRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::world_manager_msgs::AddMeshResponse> should match 
// service_traits::MD5Sum< ::world_manager_msgs::AddMesh > 
template<>
struct MD5Sum< ::world_manager_msgs::AddMeshResponse>
{
  static const char* value()
  {
    return MD5Sum< ::world_manager_msgs::AddMesh >::value();
  }
  static const char* value(const ::world_manager_msgs::AddMeshResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::world_manager_msgs::AddMeshResponse> should match 
// service_traits::DataType< ::world_manager_msgs::AddMesh > 
template<>
struct DataType< ::world_manager_msgs::AddMeshResponse>
{
  static const char* value()
  {
    return DataType< ::world_manager_msgs::AddMesh >::value();
  }
  static const char* value(const ::world_manager_msgs::AddMeshResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WORLD_MANAGER_MSGS_MESSAGE_ADDMESH_H
