// Generated by gencpp from file world_manager_msgs/AddTF.msg
// DO NOT EDIT!


#ifndef WORLD_MANAGER_MSGS_MESSAGE_ADDTF_H
#define WORLD_MANAGER_MSGS_MESSAGE_ADDTF_H

#include <ros/service_traits.h>


#include <world_manager_msgs/AddTFRequest.h>
#include <world_manager_msgs/AddTFResponse.h>


namespace world_manager_msgs
{

struct AddTF
{

typedef AddTFRequest Request;
typedef AddTFResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTF
} // namespace world_manager_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::world_manager_msgs::AddTF > {
  static const char* value()
  {
    return "7628ce852ab5e9d13813162d145212da";
  }

  static const char* value(const ::world_manager_msgs::AddTF&) { return value(); }
};

template<>
struct DataType< ::world_manager_msgs::AddTF > {
  static const char* value()
  {
    return "world_manager_msgs/AddTF";
  }

  static const char* value(const ::world_manager_msgs::AddTF&) { return value(); }
};


// service_traits::MD5Sum< ::world_manager_msgs::AddTFRequest> should match 
// service_traits::MD5Sum< ::world_manager_msgs::AddTF > 
template<>
struct MD5Sum< ::world_manager_msgs::AddTFRequest>
{
  static const char* value()
  {
    return MD5Sum< ::world_manager_msgs::AddTF >::value();
  }
  static const char* value(const ::world_manager_msgs::AddTFRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::world_manager_msgs::AddTFRequest> should match 
// service_traits::DataType< ::world_manager_msgs::AddTF > 
template<>
struct DataType< ::world_manager_msgs::AddTFRequest>
{
  static const char* value()
  {
    return DataType< ::world_manager_msgs::AddTF >::value();
  }
  static const char* value(const ::world_manager_msgs::AddTFRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::world_manager_msgs::AddTFResponse> should match 
// service_traits::MD5Sum< ::world_manager_msgs::AddTF > 
template<>
struct MD5Sum< ::world_manager_msgs::AddTFResponse>
{
  static const char* value()
  {
    return MD5Sum< ::world_manager_msgs::AddTF >::value();
  }
  static const char* value(const ::world_manager_msgs::AddTFResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::world_manager_msgs::AddTFResponse> should match 
// service_traits::DataType< ::world_manager_msgs::AddTF > 
template<>
struct DataType< ::world_manager_msgs::AddTFResponse>
{
  static const char* value()
  {
    return DataType< ::world_manager_msgs::AddTF >::value();
  }
  static const char* value(const ::world_manager_msgs::AddTFResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WORLD_MANAGER_MSGS_MESSAGE_ADDTF_H
