// Generated by gencpp from file world_manager_msgs/SceneObject.msg
// DO NOT EDIT!


#ifndef WORLD_MANAGER_MSGS_MESSAGE_SCENEOBJECT_H
#define WORLD_MANAGER_MSGS_MESSAGE_SCENEOBJECT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/PoseStamped.h>

namespace world_manager_msgs
{
template <class ContainerAllocator>
struct SceneObject_
{
  typedef SceneObject_<ContainerAllocator> Type;

  SceneObject_()
    : object_name()
    , mesh_filepath()
    , pose_stamped()  {
    }
  SceneObject_(const ContainerAllocator& _alloc)
    : object_name(_alloc)
    , mesh_filepath(_alloc)
    , pose_stamped(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _object_name_type;
  _object_name_type object_name;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _mesh_filepath_type;
  _mesh_filepath_type mesh_filepath;

   typedef  ::geometry_msgs::PoseStamped_<ContainerAllocator>  _pose_stamped_type;
  _pose_stamped_type pose_stamped;





  typedef boost::shared_ptr< ::world_manager_msgs::SceneObject_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::world_manager_msgs::SceneObject_<ContainerAllocator> const> ConstPtr;

}; // struct SceneObject_

typedef ::world_manager_msgs::SceneObject_<std::allocator<void> > SceneObject;

typedef boost::shared_ptr< ::world_manager_msgs::SceneObject > SceneObjectPtr;
typedef boost::shared_ptr< ::world_manager_msgs::SceneObject const> SceneObjectConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::world_manager_msgs::SceneObject_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::world_manager_msgs::SceneObject_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace world_manager_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'world_manager_msgs': ['/home/student/smoothiebot_ws/src/world_manager/world_manager_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::world_manager_msgs::SceneObject_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::world_manager_msgs::SceneObject_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::world_manager_msgs::SceneObject_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::world_manager_msgs::SceneObject_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::world_manager_msgs::SceneObject_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::world_manager_msgs::SceneObject_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::world_manager_msgs::SceneObject_<ContainerAllocator> >
{
  static const char* value()
  {
    return "20f36b7419e69e39d65a739459b9e19b";
  }

  static const char* value(const ::world_manager_msgs::SceneObject_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x20f36b7419e69e39ULL;
  static const uint64_t static_value2 = 0xd65a739459b9e19bULL;
};

template<class ContainerAllocator>
struct DataType< ::world_manager_msgs::SceneObject_<ContainerAllocator> >
{
  static const char* value()
  {
    return "world_manager_msgs/SceneObject";
  }

  static const char* value(const ::world_manager_msgs::SceneObject_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::world_manager_msgs::SceneObject_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string object_name\n\
string mesh_filepath\n\
geometry_msgs/PoseStamped pose_stamped\n\
================================================================================\n\
MSG: geometry_msgs/PoseStamped\n\
# A Pose with reference coordinate frame and timestamp\n\
Header header\n\
Pose pose\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of position and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
";
  }

  static const char* value(const ::world_manager_msgs::SceneObject_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::world_manager_msgs::SceneObject_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.object_name);
      stream.next(m.mesh_filepath);
      stream.next(m.pose_stamped);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SceneObject_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::world_manager_msgs::SceneObject_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::world_manager_msgs::SceneObject_<ContainerAllocator>& v)
  {
    s << indent << "object_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.object_name);
    s << indent << "mesh_filepath: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.mesh_filepath);
    s << indent << "pose_stamped: ";
    s << std::endl;
    Printer< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.pose_stamped);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WORLD_MANAGER_MSGS_MESSAGE_SCENEOBJECT_H
