# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from world_manager_msgs/AddBoxRequest.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import world_manager_msgs.msg
import geometry_msgs.msg
import std_msgs.msg

class AddBoxRequest(genpy.Message):
  _md5sum = "ead51e2681bda79a8bd2c56ad0252ea0"
  _type = "world_manager_msgs/AddBoxRequest"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """world_manager_msgs/SceneBox scene_box

================================================================================
MSG: world_manager_msgs/SceneBox
string object_name
geometry_msgs/PoseStamped pose_stamped
float32 edge_length_x
float32 edge_length_y
float32 edge_length_z
================================================================================
MSG: geometry_msgs/PoseStamped
# A Pose with reference coordinate frame and timestamp
Header header
Pose pose

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id

================================================================================
MSG: geometry_msgs/Pose
# A representation of pose in free space, composed of position and orientation. 
Point position
Quaternion orientation

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w
"""
  __slots__ = ['scene_box']
  _slot_types = ['world_manager_msgs/SceneBox']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       scene_box

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(AddBoxRequest, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.scene_box is None:
        self.scene_box = world_manager_msgs.msg.SceneBox()
    else:
      self.scene_box = world_manager_msgs.msg.SceneBox()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.scene_box.object_name
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_3I().pack(_x.scene_box.pose_stamped.header.seq, _x.scene_box.pose_stamped.header.stamp.secs, _x.scene_box.pose_stamped.header.stamp.nsecs))
      _x = self.scene_box.pose_stamped.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_7d3f().pack(_x.scene_box.pose_stamped.pose.position.x, _x.scene_box.pose_stamped.pose.position.y, _x.scene_box.pose_stamped.pose.position.z, _x.scene_box.pose_stamped.pose.orientation.x, _x.scene_box.pose_stamped.pose.orientation.y, _x.scene_box.pose_stamped.pose.orientation.z, _x.scene_box.pose_stamped.pose.orientation.w, _x.scene_box.edge_length_x, _x.scene_box.edge_length_y, _x.scene_box.edge_length_z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.scene_box is None:
        self.scene_box = world_manager_msgs.msg.SceneBox()
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.scene_box.object_name = str[start:end].decode('utf-8')
      else:
        self.scene_box.object_name = str[start:end]
      _x = self
      start = end
      end += 12
      (_x.scene_box.pose_stamped.header.seq, _x.scene_box.pose_stamped.header.stamp.secs, _x.scene_box.pose_stamped.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.scene_box.pose_stamped.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.scene_box.pose_stamped.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 68
      (_x.scene_box.pose_stamped.pose.position.x, _x.scene_box.pose_stamped.pose.position.y, _x.scene_box.pose_stamped.pose.position.z, _x.scene_box.pose_stamped.pose.orientation.x, _x.scene_box.pose_stamped.pose.orientation.y, _x.scene_box.pose_stamped.pose.orientation.z, _x.scene_box.pose_stamped.pose.orientation.w, _x.scene_box.edge_length_x, _x.scene_box.edge_length_y, _x.scene_box.edge_length_z,) = _get_struct_7d3f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.scene_box.object_name
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_3I().pack(_x.scene_box.pose_stamped.header.seq, _x.scene_box.pose_stamped.header.stamp.secs, _x.scene_box.pose_stamped.header.stamp.nsecs))
      _x = self.scene_box.pose_stamped.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_7d3f().pack(_x.scene_box.pose_stamped.pose.position.x, _x.scene_box.pose_stamped.pose.position.y, _x.scene_box.pose_stamped.pose.position.z, _x.scene_box.pose_stamped.pose.orientation.x, _x.scene_box.pose_stamped.pose.orientation.y, _x.scene_box.pose_stamped.pose.orientation.z, _x.scene_box.pose_stamped.pose.orientation.w, _x.scene_box.edge_length_x, _x.scene_box.edge_length_y, _x.scene_box.edge_length_z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.scene_box is None:
        self.scene_box = world_manager_msgs.msg.SceneBox()
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.scene_box.object_name = str[start:end].decode('utf-8')
      else:
        self.scene_box.object_name = str[start:end]
      _x = self
      start = end
      end += 12
      (_x.scene_box.pose_stamped.header.seq, _x.scene_box.pose_stamped.header.stamp.secs, _x.scene_box.pose_stamped.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.scene_box.pose_stamped.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.scene_box.pose_stamped.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 68
      (_x.scene_box.pose_stamped.pose.position.x, _x.scene_box.pose_stamped.pose.position.y, _x.scene_box.pose_stamped.pose.position.z, _x.scene_box.pose_stamped.pose.orientation.x, _x.scene_box.pose_stamped.pose.orientation.y, _x.scene_box.pose_stamped.pose.orientation.z, _x.scene_box.pose_stamped.pose.orientation.w, _x.scene_box.edge_length_x, _x.scene_box.edge_length_y, _x.scene_box.edge_length_z,) = _get_struct_7d3f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_7d3f = None
def _get_struct_7d3f():
    global _struct_7d3f
    if _struct_7d3f is None:
        _struct_7d3f = struct.Struct("<7d3f")
    return _struct_7d3f
# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from world_manager_msgs/AddBoxResponse.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class AddBoxResponse(genpy.Message):
  _md5sum = "d41d8cd98f00b204e9800998ecf8427e"
  _type = "world_manager_msgs/AddBoxResponse"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """
"""
  __slots__ = []
  _slot_types = []

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(AddBoxResponse, self).__init__(*args, **kwds)

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      pass
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      pass
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
class AddBox(object):
  _type          = 'world_manager_msgs/AddBox'
  _md5sum = 'ead51e2681bda79a8bd2c56ad0252ea0'
  _request_class  = AddBoxRequest
  _response_class = AddBoxResponse
